---
server:
  port: 9999

spring:
  cloud:
    config:
      server:
        git:
          uri: file://Users/esb19600/Documents/ConfigData
          searchPaths: demo-cloud-config
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
